# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
kotlin = "2.3.10"
kotlinxSerializationJSON = "1.10.0"
ktor = "3.4.0"
openhtmltopdf = "1.1.37"
logback = "1.5.28"
verapdf = "1.28.2"
jsoup = "1.18.3"

[libraries]
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinxSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJSON" }

# Ktor Server
ktorServerCore = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktorServerNetty = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor" }
ktorServerContentNegotiation = { module = "io.ktor:ktor-server-content-negotiation-jvm", version.ref = "ktor" }
ktorServerCallLogging = { module = "io.ktor:ktor-server-call-logging-jvm", version.ref = "ktor" }
ktorServerStatusPages = { module = "io.ktor:ktor-server-status-pages-jvm", version.ref = "ktor" }
ktorServerAuth = { module = "io.ktor:ktor-server-auth-jvm", version.ref = "ktor" }
ktorServerMustache = { module = "io.ktor:ktor-server-mustache-jvm", version.ref = "ktor" }
ktorSerializationJson = { module = "io.ktor:ktor-serialization-kotlinx-json-jvm", version.ref = "ktor" }

# OpenHTMLToPDF
openhtmltopdfCore = { module = "io.github.openhtmltopdf:openhtmltopdf-core", version.ref = "openhtmltopdf" }
openhtmltopdfPdfbox = { module = "io.github.openhtmltopdf:openhtmltopdf-pdfbox", version.ref = "openhtmltopdf" }

# HTML Parser
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }

# Logging
logbackClassic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

# Testing
ktorServerTestHost = { module = "io.ktor:ktor-server-test-host-jvm", version.ref = "ktor" }
kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

# veraPDF Validation
verapdfValidation = { module = "org.verapdf:validation-model", version.ref = "verapdf" }
verapdfCore = { module = "org.verapdf:core", version.ref = "verapdf" }

[plugins]
kotlinPluginSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }